[package]
name = "m2mfstaligner"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.68"
rustfst = "0.11.6"
string-join = "0.1.2"
csv = "1.1"
unicode-segmentation = "1.10.1"