[package]
name = "m2mfstaligner"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
rustfst.workspace = true
string-join = "0.1.2"
csv = "1.1"
unicode-segmentation = "1.10.1"